image: gitpod/workspace-full

tasks:
  - name: Restore dependencies
    init: |
      mkdir -p "$DOTNET_ROOT"
      wget --output-document="$DOTNET_ROOT/dotnet-install.sh" https://dot.net/v1/dotnet-install.sh
      chmod +x "$DOTNET_ROOT/dotnet-install.sh"
      "$DOTNET_ROOT/dotnet-install.sh" --channel 10.0 --install-dir "$DOTNET_ROOT"
      dotnet restore

vscode:
  extensions:
    - muhammad-sammy.csharp
